"""Habit inference: daily-cached aggregation of estimates.jsonl.

Regenerated by SessionStart if habits.json is stale (>24 hours).
Protected by .habits.lock to prevent concurrent SessionStart races.
"""

from __future__ import annotations

import datetime
import json
import sys
from typing import Optional


def _compute_habits(entries: list[dict]) -> dict:
    """Aggregate JSONL entries into a habits summary dict."""
    import statistics as stats

    completed = [
        e for e in entries
        if e.get("status") in ("completed", "tentative")
        and e.get("active_minutes") is not None
    ]

    # Typical work hours from started_at timestamps
    work_hours: list[int] = []
    for e in completed:
        ts_str = e.get("started_at") or e.get("estimated_at")
        if ts_str:
            try:
                dt = datetime.datetime.fromisoformat(ts_str)
                work_hours.append(dt.hour)
            except Exception:
                pass

    typical_work_hours: dict = {}
    if work_hours:
        typical_work_hours = {
            "start": f"{min(work_hours):02d}:00",
            "end": f"{max(work_hours):02d}:59",
            "confidence": min(0.95, len(work_hours) / 50),
        }

    # Day distribution
    day_part_counts: dict[str, int] = {
        "early-morning": 0, "morning": 0, "midday": 0,
        "afternoon": 0, "evening": 0, "night": 0, "late-night": 0,
    }
    weekend_active = False
    for h in work_hours:
        if h < 5:
            day_part_counts["late-night"] += 1
        elif h < 9:
            day_part_counts["early-morning"] += 1
        elif h < 12:
            day_part_counts["morning"] += 1
        elif h < 14:
            day_part_counts["midday"] += 1
        elif h < 18:
            day_part_counts["afternoon"] += 1
        elif h < 21:
            day_part_counts["evening"] += 1
        else:
            day_part_counts["night"] += 1

    total_hours = max(len(work_hours), 1)
    day_part_dist = {k: round(v / total_hours, 3) for k, v in day_part_counts.items()}

    active_minutes_list: list[float] = []
    elapsed_minutes_list: list[float] = []

    for e in completed:
        am = e.get("active_minutes")
        em = e.get("elapsed_minutes")
        if am is not None and am > 0:
            active_minutes_list.append(float(am))
        if em is not None and em > 0:
            elapsed_minutes_list.append(float(em))

    median_session = round(stats.median(active_minutes_list), 1) if active_minutes_list else 0
    active_to_elapsed = 0.0
    if active_minutes_list and elapsed_minutes_list:
        ratios = [
            a / e for a, e in zip(active_minutes_list, elapsed_minutes_list)
            if e > 0
        ]
        if ratios:
            active_to_elapsed = round(stats.median(ratios), 3)

    # Per-category velocity
    category_velocity: dict = {}
    import statistics as stats2
    cats = set(e.get("category", "uncategorized") for e in completed)
    for cat in cats:
        cat_entries = [e for e in completed if e.get("category") == cat]
        actuals = [e["active_minutes"] for e in cat_entries if e.get("active_minutes", 0) > 0]
        if actuals:
            category_velocity[cat] = {
                "median_minutes": round(stats2.median(actuals), 1),
                "n": len(actuals),
            }

    # Last activity and current streak
    last_activity: Optional[str] = None
    current_streak_minutes = 0

    if entries:
        ts_list = []
        for e in entries:
            ts_str = e.get("completed_at") or e.get("estimated_at")
            if ts_str:
                try:
                    ts_list.append(datetime.datetime.fromisoformat(ts_str))
                except Exception:
                    pass
        if ts_list:
            latest = max(ts_list)
            last_activity = latest.isoformat()
            # Streak: sum active_minutes from today
            today = datetime.datetime.utcnow().date()
            today_entries = [
                e for e in completed
                if (e.get("estimated_at") or "")[:10] == str(today)
            ]
            current_streak_minutes = int(sum(
                e.get("active_minutes", 0) or 0 for e in today_entries
            ))

    return {
        "_computed_at": datetime.datetime.utcnow().isoformat() + "Z",
        "typical_work_hours": typical_work_hours,
        "weekend_active": weekend_active,
        "median_session_length_minutes": median_session,
        "median_continuous_work_minutes": median_session,
        "category_velocity": category_velocity,
        "day_part_distribution": day_part_dist,
        "active_to_elapsed_ratio_median": active_to_elapsed,
        "last_activity": last_activity,
        "current_streak_minutes": current_streak_minutes,
    }


def refresh_if_stale(force: bool = False) -> bool:
    """Refresh habits.json if stale (>24h) or forced.

    Uses a .habits.lock file to prevent concurrent refresh races.
    Returns True if refresh was performed.
    """
    from pocket_watch.paths import data_dir, habits_path
    from pocket_watch.log import read_all

    hp = habits_path()
    dd = data_dir()
    lock_path = dd / ".habits.lock"

    # Check freshness
    if not force and hp.exists():
        try:
            mtime = datetime.datetime.fromtimestamp(hp.stat().st_mtime, tz=datetime.timezone.utc)
            age = datetime.datetime.now(tz=datetime.timezone.utc) - mtime
            if age.total_seconds() < 86400:  # 24 hours
                return False
        except Exception:
            pass

    # Try to acquire lock (non-blocking)
    if sys.platform != "win32":
        import fcntl

        try:
            lock_fd = open(lock_path, "w")
            fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except (BlockingIOError, OSError):
            # Another hook is refreshing — skip this fire
            return False
    else:
        lock_fd = None  # Windows: best-effort, no lock

    try:
        entries = read_all()
        habits = _compute_habits(entries)
        tmp = hp.with_suffix(".tmp")
        tmp.write_text(json.dumps(habits, indent=2, default=str), encoding="utf-8")
        tmp.replace(hp)
        return True
    except Exception:
        return False
    finally:
        if lock_fd is not None:
            try:
                import fcntl
                fcntl.flock(lock_fd, fcntl.LOCK_UN)
                lock_fd.close()
            except Exception:
                pass
        if lock_path.exists():
            try:
                lock_path.unlink()
            except Exception:
                pass


def load_habits() -> dict:
    """Load habits.json, returning empty dict if missing or corrupt."""
    from pocket_watch.paths import habits_path

    hp = habits_path()
    if not hp.exists():
        return {}
    try:
        return json.loads(hp.read_text(encoding="utf-8"))
    except Exception:
        return {}
